;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	end-of-buffer
	keyboard-escape-quit
	multiple-cursors-mode
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	dap-tooltip-mouse-motion
	lsp-signature-stop
	tuareg-eval-phrase
	))
